
import {ArrowRight, Check, CheckCircle, ChevronsUpDown, Circle, Copy, Edit, ExternalLink, File, HelpCircle, Home, Loader2, Mail, MessageSquare, Mic, Moon, PanelLeft, Plus, PlusCircle, RefreshCw, Search, Server, Settings, Share2, Shield, Sun, Trash, User, Upload, Camera, X, XCircle, AlertCircle, Sparkles, Workflow} from 'lucide-react';

const Icons = {
  arrowRight: ArrowRight,
  check: Check,
  checkCircle: CheckCircle,
  chevronDown: ChevronsUpDown,
  circle: Circle,
  workflow: Workflow,
  close: X,
  x: X,
  copy: Copy,
  dark: Moon,
  edit: Edit,
  externalLink: ExternalLink,
  file: File,
  help: HelpCircle,
  home: Home,
  light: Sun,
  loader: Loader2,
  mail: Mail,
  messageSquare: MessageSquare,
  mic: Mic,
  plus: Plus,
  plusCircle: PlusCircle,
  refreshCw: RefreshCw,
  search: Search,
  server: Server,
  settings: Settings,
  share: Share2,
  shield: Shield,
  spinner: Loader2,
  trash: Trash,
  user: User,
  panelLeft: PanelLeft,
  upload: Upload,
  camera: Camera,
  alertCircle: AlertCircle,
  xCircle: XCircle,
  sparkles: Sparkles,
};

export {Icons};
